const CHANGE_THEME = "CHANGE_THEME";

const INITIALIZED_SUCCESS = "INITIALIZED_SUCCESS";

const AUTH_LOADED = "AUTH_LOADED";
const AUTH_SUCCESS = "AUTH_SUCCESS";
const AUTH_LOGOUT = "AUTH_LOGOUT";
const AUTH_ERROR = "AUTH_ERROR";

const SET_NAME = "SET_NAME";
const CLEAN_NAME = "CLEAN_NAME";

const GET_NOTES_LOADED = "GET_NOTES_LOADED";
const GET_NOTES_SUCCESS = "GET_NOTES_SUCCESS";
const GET_NOTES_ERROR = "GET_NOTES_ERROR";

const CREATE_NOTE = "CREATE_NOTE";
const REZET_NOTE = "REZET_NOTE";

const EDIT_NOTE = "EDIT_NOTE";
const SAVE_EDIT_NOTE = "SAVE_EDIT_NOTE";
const DELETE_NOTE = "DELETE_NOTE";
const VISIBLE_BLOCK_NOTES = "VISIBLE_BLOCK_NOTES";

export {
  CHANGE_THEME,
  INITIALIZED_SUCCESS,
  AUTH_LOADED,
  AUTH_SUCCESS,
  AUTH_LOGOUT,
  AUTH_ERROR,
  SET_NAME,
  CLEAN_NAME,
  GET_NOTES_LOADED,
  GET_NOTES_SUCCESS,
  GET_NOTES_ERROR,
  CREATE_NOTE,
  REZET_NOTE,
  EDIT_NOTE,
  SAVE_EDIT_NOTE,
  DELETE_NOTE,
  VISIBLE_BLOCK_NOTES,
};
