const CHANGE_THEME = "CHANGE_THEME";

const INITIALIZED_SUCCESS = "INITIALIZED_SUCCESS";

const AUTH_LOADED = "AUTH_LOADED";
const AUTH_SUCCESS = "AUTH_SUCCESS";
const AUTH_LOGOUT = "AUTH_LOGOUT";
const AUTH_ERROR = "AUTH_ERROR";

const SET_NAME = "SET_NAME";
const CLEAN_NAME = "CLEAN_NAME";

const GET_NOTES_LOADED = "GET_NOTES_LOADED";
const GET_NOTES_SUCCESS = "GET_NOTES_SUCCESS";
const GET_NOTES_ERROR = "GET_NOTES_ERROR";

const CREATE_NOTE = "CREATE_NOTE";
const REZET_NOTE = "REZET_NOTE";

const EDIT_NOTE = "EDIT_NOTE";
const SAVE_EDIT_NOTE = "SAVE_EDIT_NOTE";
const DELETE_NOTE = "DELETE_NOTE";
const LIKE_NOTE = "LIKE_NOTE";
const READY_NOTE = "READY_NOTE";
const VISIBLE_BLOCK_NOTES = "VISIBLE_BLOCK_NOTES";
const FILTER_BY_DATE = "FILTER_BY_DATE";
const RESET_FILTER_BY_DATE = "RESET_FILTER_BY_DATE";
const SET_NOTE_STYLE = "SET_NOTE_STYLE";
const SET_SEARCH_NOTES_LIST = "SET_SEARCH_NOTES_LIST";

export {
  CHANGE_THEME,
  INITIALIZED_SUCCESS,
  AUTH_LOADED,
  AUTH_SUCCESS,
  AUTH_LOGOUT,
  AUTH_ERROR,
  SET_NAME,
  CLEAN_NAME,
  GET_NOTES_LOADED,
  GET_NOTES_SUCCESS,
  GET_NOTES_ERROR,
  CREATE_NOTE,
  REZET_NOTE,
  EDIT_NOTE,
  SAVE_EDIT_NOTE,
  DELETE_NOTE,
  LIKE_NOTE,
  READY_NOTE,
  VISIBLE_BLOCK_NOTES,
  FILTER_BY_DATE,
  SET_NOTE_STYLE,
  SET_SEARCH_NOTES_LIST,
  RESET_FILTER_BY_DATE,
};
