const CHANGE_THEME = "CHANGE_THEME";

const INITIALIZED_SUCCESS = "INITIALIZED_SUCCESS";

const AUTH_LOADED = "AUTH_LOADED";
const AUTH_SUCCESS = "AUTH_SUCCESS";
const AUTH_LOGOUT = "AUTH_LOGOUT";
const AUTH_ERROR = "AUTH_ERROR";

const SET_NAME = "SET_NAME";
const CLEAN_NAME = "CLEAN_NAME";

export {
  CHANGE_THEME,
  INITIALIZED_SUCCESS,
  AUTH_LOADED,
  AUTH_SUCCESS,
  AUTH_LOGOUT,
  AUTH_ERROR,
  SET_NAME,
  CLEAN_NAME,
};
